FROM python:3.9-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    software-properties-common \
    git \
    && rm -rf /var/lib/apt/lists/*

RUN git clone https://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@github.com/deveucatur/cadastro_9Box.git .

RUN pip3 install -r requirements.txt

EXPOSE 8502

HEALTHCHECK CMD curl --fail http://localhost:8502/_stcore/health

ENTRYPOINT ["streamlit", "run", "Cadastro.py", "--server.port=8502", "--server.address=0.0.0.0"]
